spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_gestao_estacionamento
    username: admin
    password: x99011
    hikari:
      poolName: gestao-estacionamento-connection-pool
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
